<a href="https://colab.research.google.com/github/bert13069598/Embedded_System/blob/master/Lecture18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

data = [[1,2],[3,4]]
x_data=torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


## Tensor : volumetric data structure

In [ ]:
shape=(2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print("Random Tensor: \n", rand_tensor)
print("Ones Tensor: \n", ones_tensor)
print("Zeros Tensor: \n", zeros_tensor)

Random Tensor: 
 tensor([[0.4221, 0.4177, 0.1636],
        [0.5931, 0.2122, 0.2822]])
Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Basic operations : transposing, slicing, indexing, etc.

In [ ]:
data = [[1,2,3,4],[0,1,0,1],[5,6,7,8],[3,3,9,9]]
tensor=torch.tensor(data)

# Move tensor to GPU
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

print(tensor)
print('First row:',tensor[0])
print('First column:',tensor[:,0])
print('Last column:',tensor[...,-1])
tensor[:,1] = 0
print(tensor)

tensor([[1, 2, 3, 4],
        [0, 1, 0, 1],
        [5, 6, 7, 8],
        [3, 3, 9, 9]])
First row: tensor([1, 2, 3, 4])
First column: tensor([1, 0, 5, 3])
Last column: tensor([4, 1, 8, 9])
tensor([[1, 0, 3, 4],
        [0, 0, 0, 1],
        [5, 0, 7, 8],
        [3, 0, 9, 9]])


In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])
x_trans = torch.transpose(x,0,1) # shape 0번째와 1번째 맞바꿈
print(x.shape)
print(x)
print(x_trans.shape)
print(x_trans)

torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([3, 2])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [ ]:
x=torch.tensor([[[[1,2,3],
                 [4,5,6],
                 [7,8,9]]],
               [[[-1,-2,-3],
                 [-4,-5,-6],
                 [-7,-8,-9]]]])
print(x.shape)
print(x)
y=torch.transpose(x,1,2)
print("\n")
print(y.size())
print(y)

torch.Size([2, 1, 3, 3])
tensor([[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]]],


        [[[-1, -2, -3],
          [-4, -5, -6],
          [-7, -8, -9]]]])


torch.Size([2, 3, 1, 3])
tensor([[[[ 1,  2,  3]],

         [[ 4,  5,  6]],

         [[ 7,  8,  9]]],


        [[[-1, -2, -3]],

         [[-4, -5, -6]],

         [[-7, -8, -9]]]])


## Tensor reshape : .view

In [ ]:
x = torch.tensor([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])
print(x)
y=x.view(16)
print(y)
z=x.view(2,-1)
print(z)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16]])


In [ ]:
x=torch.tensor([[[1,2],[3,4]],
                [[5,6],[7,8]],
                [[9,10],[11,12]]])
print(x.shape)
print(x)

y=x.view(-1,3)
print(y.size())
print(y)

z=x.view(-1,2,3)
print(z.size())
print(z)

torch.Size([3, 2, 2])
tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])
torch.Size([4, 3])
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
torch.Size([2, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


## Tensor reshape : squeeze and unsqueeze

In [ ]:
x=torch.tensor([[1],[2],[3]])
print(x.size())
y=x.squeeze()
print(y.size())

x=torch.tensor([1,2,3])
y=x.unsqueeze(0)
z=x.unsqueeze(-1)
print(y.size())
print(z.size())

torch.Size([3, 1])
torch.Size([3])
torch.Size([1, 3])
torch.Size([3, 1])


## Tensor concatenation

In [ ]:
data=[[1,2,3,4],[0,1,0,1],[5,6,7,8],[3,3,9,9]]
tensor = torch.tensor(data)
print(tensor)

tensor_concat = torch.cat([tensor,tensor],dim=1)
print(tensor_concat)
tensor_concat = torch.cat([tensor,tensor],dim=0)
print(tensor_concat)

tensor([[1, 2, 3, 4],
        [0, 1, 0, 1],
        [5, 6, 7, 8],
        [3, 3, 9, 9]])
tensor([[1, 2, 3, 4, 1, 2, 3, 4],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [5, 6, 7, 8, 5, 6, 7, 8],
        [3, 3, 9, 9, 3, 3, 9, 9]])
tensor([[1, 2, 3, 4],
        [0, 1, 0, 1],
        [5, 6, 7, 8],
        [3, 3, 9, 9],
        [1, 2, 3, 4],
        [0, 1, 0, 1],
        [5, 6, 7, 8],
        [3, 3, 9, 9]])


## Arithmetic operations : addition, subtraction, multiplication, etc.

In [ ]:
x=torch.tensor([[1,1,1],[2,2,2]])
x_mul=torch.mul(x,100)
print(x)
print(x_mul)

tensor([[1, 1, 1],
        [2, 2, 2]])
tensor([[100, 100, 100],
        [200, 200, 200]])


In [ ]:
x=torch.tensor([[2,2,2],[4,4,4]])
y=3*torch.ones(x.size())
z=x*y
print(x)
print(y)
print(z)

tensor([[2, 2, 2],
        [4, 4, 4]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
tensor([[ 6.,  6.,  6.],
        [12., 12., 12.]])
